FROM node:20-alpine3.17

WORKDIR /app

COPY . .

RUN npm i

RUN sudo apt update -y
RUN apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev -y
RUN sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev -y
RUN sudo apt-get install libasound2 -y
RUN sudo apt upgrade -y

CMD [ "node", "src/fork.js" ]